In [8]:
import numpy as np
import ot

# Initialize 1D histograms a and b (must sum to 1 and be positive)
a = np.array([0.5, 0.3, 0.2])  # 3-element distribution
b = np.array([0.2, 0.5, 0.3])  # 3-element distribution

# Initialize ground cost matrix M (3x3)
M = np.array([[0., 1., 2.],
              [1., 0., 1.],
              [2., 1., 0.]])

# Regularization parameter
reg = 0.1

### Compute Wasserstein distances

In [9]:
# a,b are 1D histograms (sum to 1 and positive)
# M is the ground cost matrix

# With the unified  API :
Wd = ot.solve(M, a, b).value                # exact linear program
Wd_reg = ot.solve(M, a, b, reg=reg).value   # entropic regularized OT

# Print
print(Wd)
print(Wd_reg)

0.39999999999999997
0.44228104473030666


### Compute OT matrix

In [10]:
# a,b are 1D histograms (sum to 1 and positive)
# M is the ground cost matrix

# With the unified API :
T = ot.solve(M, a, b).plan # exact linear program
T_reg = ot.solve(M, a, b, reg=reg).plan # entropic regularized 

# Print
print(T)
print(T_reg)

[[0.2 0.3 0. ]
 [0.  0.2 0.1]
 [0.  0.  0.2]]
[[2.00000000e-01 2.49999999e-01 5.00000009e-02]
 [4.12230723e-10 2.49999999e-01 5.00000007e-02]
 [3.39868331e-18 2.06115356e-09 1.99999998e-01]]


In [11]:
# Initialize X and Y as 2D arrays of shape (n_samples, n_features)
np.random.seed(42)
n_samples_X = 5
n_samples_Y = 4
n_features = 2

X = np.random.randn(n_samples_X, n_features)  # 5 samples, 2 features
Y = np.random.randn(n_samples_Y, n_features)  # 4 samples, 2 features

print("X shape:", X.shape)
print("Y shape:", Y.shape)
print(X)
print(Y)

X shape: (5, 2)
Y shape: (4, 2)
[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]]
[[-0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024]
 [-1.72491783 -0.56228753]
 [-1.01283112  0.31424733]]


### Compute OT on empirical distributions

In [12]:
# X and Y are two 2D arrays of shape (n_samples, n_features)

# with squared euclidean metric
T = ot.solve_sample(X, Y).plan # exact linear program
T_reg = ot.solve_sample(X, Y, reg=reg).plan # entropic regularized OT

print(T)
print(T_reg)

Wass_2 = ot.solve_sample(X, Y).value # Squared Wasserstein_2
Wass_1 = ot.solve_sample(X, Y, metric='euclidean').value # Wasserstein 1

print("Squared Wasserstein-2:", Wass_2)
print("Wasserstein-1:", Wass_1)

[[0.   0.2  0.   0.  ]
 [0.   0.   0.   0.2 ]
 [0.05 0.05 0.1  0.  ]
 [0.2  0.   0.   0.  ]
 [0.   0.   0.15 0.05]]
[[1.28726156e-04 1.99871274e-01 1.96316002e-12 4.10400958e-12]
 [1.83077551e-04 3.09618396e-21 2.50235351e-15 1.99816922e-01]
 [5.40574544e-02 4.48181379e-02 1.01123220e-01 1.18764038e-06]
 [1.94689354e-01 5.31058795e-03 7.10919908e-22 5.79387347e-08]
 [9.41387515e-04 4.84142526e-15 1.48876780e-01 5.01818324e-02]]
Squared Wasserstein-2: 3.4529375277616325
Wasserstein-1: 1.7173111409202477


### Compute Wasserstein barycenter

In [13]:
# Initialize A as an n*d matrix containing d 1D histograms
# Each row is a 1D histogram that sums to 1
n_histograms = 3
n_bins = 4

A = np.array([[0.5, 0.3, 0.2, 0.0],
              [0.2, 0.3, 0.3, 0.2],
              [0.1, 0.2, 0.3, 0.4]])  # n=3 histograms, d=4 bins each

# Initialize ground cost matrix M (4x4 for the 4 bins)
M = np.array([[0., 1., 2., 3.],
              [1., 0., 1., 2.],
              [2., 1., 0., 1.],
              [3., 2., 1., 0.]])

print("\nM (cost matrix):\n", M)


M (cost matrix):
 [[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]
 [3. 2. 1. 0.]]


In [14]:
# A is a n*d matrix containing d  1D histograms
# M is the ground cost matrix
reg = 0.1
ba = ot.barycenter(A.T, M, reg) # reg is regularization parameter

print("Barycenter:", ba)

Barycenter: [0.20001437 0.29997512 0.30000024 0.20001027]
